name: 'Codewatchers Commit Notifier'
description: 'Prepares commit notifications by matching changed files with CODEOWNERS rules'
author: 'Dmitry Gurovich <yrtimid@gmail.com>'
inputs:
  GITHUB_TOKEN:
    description: 'The GitHub token used to create an authenticated client. Must have Metadata and Contents read permissions.'
    required: true
  sha_from:
    description: 'The SHA of the most recent commit on ref before the push. (ex. github.event.before)'
    required: true
  sha_to:
    description: 'The SHA of the most recent commit on ref after the push. (ex. github.event.after)'
    required: true
  codewatchers:
    description: 'Location of the CODEWATCHERS file'
    required: false
    default: '.github/CODEWATCHERS'
  codewatchers_ref:
    description: 'The ref to use when loading the CODEWATCHERS file. (using github.ref by default)'
    required: false
  ignore_own:
    description: 'Prevents notifications for own commits'
    required: false
    default: 'true'
  aggregate_files_limit:
    description: 'Limit of how much files details will be included'
    required: false
    default: '20'
  aggregate_notifications_limit:
    description: 'Limit after which many notifications will be replaces with a single aggregated summary message (for each distinct group of subscribers)'
    required: false
    default: '5'
outputs:
  notifications:
    description: 'Array of notification objects each one has two fields: "commit" (single commit details), "watchers" (array of subscribers)'
branding:
  icon: 'bell'
  color: 'green'
runs:
  using: 'node20'
  main: 'dist/index.js'
