name: 'Codewatchers Commit Notifier'
description: 'Prepares commit notifications by matching changed files with CODEOWNERS rules'
author: 'Dmitry Gurovich <yrtimid@gmail.com>'
inputs:
  GITHUB_TOKEN:
    description: 'The GitHub token used to create an authenticated client. Must have Metadata and Contents read permissions.'
    required: true
  sha_from:
    description: 'The SHA of the most recent commit on ref before the push. (ex. github.event.before)'
    required: true
  sha_to:
    description: 'The SHA of the most recent commit on ref after the push. (ex. github.event.after)'
    required: true
  codewatchers:
    description: 'Location of the CODEWATCHERS file'
    required: false
    default: '.github/CODEWATCHERS'
  ignore_own:
    description: 'Prevents notifications for own commits'
    required: false
    default: 'true'
  limit:
    description: 'Maximum number of notifications to produce. If limit exceeded - action will end with a warning and remaining commits will be skipped.'
    required: false
    default: '10'
outputs:
  notifications:
    description: 'Array of notification objects each one has next fields: "to" (string), "subj" (string) and "body" (string) '
branding:
  icon: 'bell'
  color: 'green'
runs:
  using: 'node20'
  main: 'dist/index.js'
